config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "players#index"

end

app/models/game.rb
class Game < ApplicationRecord
	default_scope { order("updated_at DESC") }

	belongs_to :white_team_first_player, class_name: "Player", foreign_key: "white_team_first_player"
	belongs_to :black_team_first_player, class_name: "Player", foreign_key: "black_team_first_player"
	belongs_to :white_team_second_player, class_name: "Player", foreign_key: "white_team_second_player", optional: true
	belongs_to :black_team_second_player, class_name: "Player", foreign_key: "black_team_second_player", optional: true

	has_many :player_results, dependent: :destroy

  	validates :white_team_first_player, presence: true
  	validates :black_team_first_player, presence: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :fetch_player_list, only: [:new, :create, :edit, :update]
  

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    setup_parameters()

    respond_to do |format|
      if @game.save
        save_individual_player_results()
        format.html { redirect_to @game, notice: 'Game was successfully saved.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    def fetch_player_list
      @all_players = Player.all
      if (@all_players.count < 2)
       redirect_to players_url, notice: 'You need more than one unique registered player to start a game.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:game_title)
    end

    def setup_parameters
      @game.white_team_first_player = Player.find(params[:white_team_first_player][:white_team_first_player_id]) if (params[:white_team_first_player][:white_team_first_player_id].present?)
      @game.white_team_second_player = Player.find(params[:white_team_second_player][:white_team_second_player_id]) if (params[:white_team_second_player][:white_team_second_player_id].present?)
      @game.black_team_first_player = Player.find(params[:black_team_first_player][:black_team_first_player_id]) if (params[:black_team_first_player][:black_team_first_player_id].present?)
      @game.black_team_second_player = Player.find(params[:black_team_second_player][:black_team_second_player_id]) if (params[:black_team_second_player][:black_team_second_player_id].present?)
      @game.result = params[:result][:result_id]
    end

    def save_individual_player_results
      # Save White Team First Player VS Opponents
      PlayerResult.create(game: @game, player: @game.white_team_first_player, teammate: @game.white_team_second_player, team: 1, opponent: @game.black_team_first_player, won: (@game.result == 1))
      PlayerResult.create(game: @game, player: @game.white_team_first_player, teammate: @game.white_team_second_player, team: 1, opponent: @game.black_team_second_player, won: (@game.result == 1)) if @game.black_team_second_player.present?

      # Save White Team Second Player VS Opponents
      if (@game.white_team_second_player.present?)
        PlayerResult.create(game: @game, player: @game.white_team_second_player, teammate: @game.white_team_first_player, team: 1, opponent: @game.black_team_first_player, won: (@game.result == 1))
        PlayerResult.create(game: @game, player: @game.white_team_second_player, teammate: @game.white_team_first_player, team: 1, opponent: @game.black_team_second_player, won: (@game.result == 1)) if @game.black_team_second_player.present?
      end

      # Save Black Team First Player VS Opponents
      PlayerResult.create(game: @game, player: @game.black_team_first_player, teammate: @game.black_team_second_player, team: 1, opponent: @game.white_team_first_player, won: (@game.result == 2))
      PlayerResult.create(game: @game, player: @game.black_team_first_player, teammate: @game.black_team_second_player, team: 1, opponent: @game.white_team_second_player, won: (@game.result == 2)) if @game.white_team_second_player.present?

      if (@game.black_team_second_player.present?)
        PlayerResult.create(game: @game, player: @game.black_team_second_player, teammate: @game.black_team_first_player, team: 1, opponent: @game.white_team_first_player, won: (@game.result == 2))
        PlayerResult.create(game: @game, player: @game.black_team_second_player, teammate: @game.black_team_first_player, team: 1, opponent: @game.white_team_second_player, won: (@game.result == 2)) if @game.white_team_second_player.present?
      end
    end

 
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :game_title %>
    <% if params[:game_title].nil? %>
      <%= form.text_field :game_title, id: :game_game_title, value: ('Match ' + game.id.to_s) %>
    <% else %>
      <%= form.text_field :game_title, id: :game_game_title %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :white_team_first_player %>
      <% if params[:white_team_first_player].present? %>
            <%= select(:white_team_first_player, :white_team_first_player_id, options_from_collection_for_select(@all_players, 'id', 'name', :selected => params[:white_team_first_player][:white_team_first_player_id]), include_blank: 'No Participant') %>
      <% else %>
            <%= select(:white_team_first_player, :white_team_first_player_id, options_from_collection_for_select(@all_players, 'id', 'name'), include_blank: 'No Participant') %>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :white_team_second_player %>
      <% if params[:white_team_second_player].present? %>
            <%= select(:white_team_second_player, :white_team_second_player_id, options_from_collection_for_select(@all_players, 'id', 'name', :selected => params[:white_team_second_player][:white_team_second_player_id]), include_blank: 'No Participant') %>
      <% else %>
            <%= select(:white_team_second_player, :white_team_second_player_id, options_from_collection_for_select(@all_players, 'id', 'name'), include_blank: 'No Participant') %>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :black_team_first_player %>
      <% if params[:black_team_first_player].present? %>
            <%= select(:black_team_first_player, :black_team_first_player_id, options_from_collection_for_select(@all_players, 'id', 'name', :selected => params[:black_team_first_player][:black_team_first_player_id]), include_blank: 'No Participant') %>
      <% else %>
            <%= select(:black_team_first_player, :black_team_first_player_id, options_from_collection_for_select(@all_players, 'id', 'name'), include_blank: 'No Participant') %>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :black_team_second_player %>
      <% if params[:black_team_second_player].present? %>
            <%= select(:black_team_second_player, :black_team_second_player_id, options_from_collection_for_select(@all_players, 'id', 'name', :selected => params[:black_team_second_player][:black_team_second_player_id]), include_blank: 'No Participant') %>
      <% else %>
            <%= select(:black_team_second_player, :black_team_second_player_id, options_from_collection_for_select(@all_players, 'id', 'name'), include_blank: 'No Participant') %>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <% if params[:result].present? %>
       <%= select(:result, :result_id, [['Tied',0], ['White Team Wins',1], ['Black Team Wins',2]], :selected => params[:result][:result_id]) %>
    <% else %>
       <%= select(:result, :result_id, [['Tied',0], ['White Team Wins',1], ['Black Team Wins',2]]) %>
    <% end %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Event Date</th>
      <th>White Team</th>
      <th></th>
      <th>Black Team</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.created_at, game %></td>
        <td>
          <% if game.result == 1 %><strong><%end%>
          <%= game.white_team_first_player.name %>
          <% if game.white_team_second_player %> and <%=game.white_team_second_player.name%> <% end %>
          <% if game.result == 1 %></strong><%end%>
        </td>
        <td> VS </td>
        <td>
          <% if game.result == 2 %><strong><%end%>
          <%= game.black_team_first_player.name %>
          <% if game.black_team_second_player %> and <%=game.black_team_second_player.name %> <% end %>
          <% if game.result == 2 %></strong><%end%>   
        </td>
        <!-- <td><%#= link_to 'X', game, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', players_path %> <%= link_to 'New Game', new_game_path %> <%= link_to 'Register New Player', new_player_path %>

app/views/games/new.html.erb
<h1>New Game</h1>
<%= link_to 'Home', players_path %> 
<%= link_to 'Register New Player', new_player_path %> 
<%= link_to 'Back', games_path %>
<%= render 'form', game: @game %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @game.game_title %> (<%= @game.created_at %>)</strong>
</p>
<p>
  <strong>White Team<%=" (WINNERS!!!)" if @game.result == 1 %>:</strong>
  <%= @game.white_team_first_player.name %>
  <%= (" and " + @game.white_team_second_player.name) if @game.white_team_second_player.present? %>
</p>

<p>
  <strong>Black Team<%=" (WINNERS!!!)" if @game.result == 2 %>:</strong>
  <%= @game.black_team_first_player.name %>
  <%= (" and " + @game.black_team_second_player.name) if @game.black_team_second_player.present? %>
</p>



<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Home', players_path %> 
<%= link_to 'Back', games_path %>