config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "players#index"

end

app/models/player.rb
class Player < ApplicationRecord
	has_many	:games
	
	scope :opponents, ->(player) { where.not(id: player) }
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @top_five_players = Player.all
    @bottom_five_players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @all_opponents = Player.opponents(@player)
    @player_games_played = PlayerResult.where(player: @player).games_played
    @player_wins = PlayerResult.where(player: @player).wins
    @player_losses = PlayerResult.where(player: @player).losses
    @player_overall_win_rate = ((@player_wins.to_f / @player_games_played.to_f) * 100) unless (@player_games_played == 0)
    @player_overall_loss_rate = ((@player_losses.to_f / @player_games_played.to_f) * 100) unless (@player_games_played == 0)
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :player_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Home', players_path %> 
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<p id="notice"><%= notice %></p>

<h1>Terem's Foosball Ranking System</h1>
<!--<h2>Search Participant: <%#= text_field_tag(:search_player_name) %> <%= submit_tag("Find") %></h2> -->
<%= link_to 'Home', players_path %> <%= link_to 'New Game', new_game_path %> <%= link_to 'Register New Player', new_player_path %>
<h2>Hall of Fame</h2>
<table>
  <thead>
    <tr>
      <th>Player Name</th>
      <th>Games Played</th>
      <th>Games Won</th>
      <th>Win Rate</th>
    </tr>
  </thead>

  <tbody>
    <% @top_five_players.each do |player| %>
      <tr>
        <td><%= link_to player.name, player %></td>
        <td><%= PlayerResult.where(player: player).games_played %></td>
        <td><%= PlayerResult.where(player: player).wins %></td>
        <td><%= number_with_precision(((PlayerResult.where(player: player).wins.to_f / PlayerResult.where(player: player).games_played.to_f) * 100), precision: 2) unless (PlayerResult.where(player: player).games_played == 0) %> %</td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Hall of Shame</h2>
<table>
  <thead>
    <tr>
      <th>Player Name</th>
      <th>Games Played</th>
      <th>Games Lost</th>
      <th>Loss Rate</th>
    </tr>
  </thead>

  <tbody>
    <% @bottom_five_players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= PlayerResult.where(player: player).games_played %></td>
        <td><%= PlayerResult.where(player: player).losses %></td>
        <td><%= number_with_precision(((PlayerResult.where(player: player).losses.to_f / PlayerResult.where(player: player).games_played.to_f) * 100), precision: 2) unless (PlayerResult.where(player: player).games_played == 0) %> %</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>
<%= link_to 'Home', players_path %> 
<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %><br/>
  Games Played:
  <%= @player_games_played %><br/>
  Wins:
  <%= @player_wins %><t/>
  Overall Win Rate:
  <%= @player_overall_win_rate %> %<br/>
  Losses:
  <%= @player_losses %><t/>
  Overall Loss Rate:
  <%= @player_overall_loss_rate %> %<br/>

  <!-- <h2>Win/Loss Rate Since Player Registered:</h2> -->
  <%#= line_chart (PlayerResult.where(playerid: @player.id).map { |result| {name: result.won, data: result.feats.linegraph}}) %>

  <h2>Win Rate Since Player Registered:</h2>
  <%= line_chart (PlayerResult.where(playerid: @player.id).linegraph_wins) %>

  <h2>Loss Rate Since Player Registered:</h2>
  <%= line_chart (PlayerResult.where(playerid: @player.id).linegraph_losses) %>

  <h2>All Opponents:</h2>
  <table>
	  <thead>
	    <tr>
	      <th>Opponents</th>
	      <th>Games Played</th>
	      <th>Wins Against This Opponent</th>
	      <th>Win Rating</th>
	      <th>Losses Against This Opponent</th>
	      <th>Loss Rating</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @all_opponents.each do |opponent| %>
	      <tr>
	        <td><%= link_to opponent.name, opponent %></td>
	        <td><%= PlayerResult.where(player: @player).against(opponent).games_played %></td>
	        <td><%= PlayerResult.where(player: @player).against(opponent).wins %></td>
	        <td><%= ((PlayerResult.where(player: @player).against(opponent).wins.to_f / PlayerResult.where(player: @player).against(opponent).games_played.to_f) * 100) unless (PlayerResult.where(player: @player).against(opponent).games_played == 0) %> %</td>
	        <td><%= ((PlayerResult.where(player: @player).against(opponent).losses.to_f / PlayerResult.where(player: @player).against(opponent).games_played.to_f) * 100) unless (PlayerResult.where(player: @player).against(opponent).games_played == 0) %> %</td>
	      </tr>
	    <% end %>
	  </tbody>
  </table>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %> <%= link_to 'Home', players_path %> 